### ISSUE TITLE
Return of regularization parameter requested

### ISSUE THREAD

**Issue by gjeschke** [luisfabib/DeerAnalysis2#18]
Sensitivity analysis may benefit from keeping the regularization parameter constant, but fitregmodel does not return it. One may also want to publish this value in some cases.

Can we have: [P,alpha] = fitregmodel(S,K,r,RegType,alpha,varargin) ?

**Comment by luisfabib** [comment]
* It is true that the optimized regularization parameter value should be returned. This is now fixed. 

* Fixing the regularization parameter for the ``sensitivan`` function did indeed provide a boost in speed. However, this is no longer needed due to the speed boosts achieved recently (see #15). 

Issue closed
