### ISSUE TITLE
Regularization parameter selection degraded since 0.8.beta

### ISSUE THREAD

**Issue by gjeschke** [luisfabib/DeerAnalysis2#26]
In two (of two) cases tested, the current commit returns significantly larger regularization parameters in 'lr' mode of regularization parameter selection than version 0.8.beta did. The old parameters were reasonable, the new ones correspond to strongly visible oversmoothing.

**Comment by luisfabib** [comment]
Could you please run two quick diagnostics for your tests? 

1) Check whether using the old search approach you can recover your previous results: 
````
alpha = selregparam(V,K,r,'tikh','lr','Search','grid');
Pfit = fitregmodel(V,K,r,'tikh',alpha)
````

2) Check how the LR-functional looks like for both search methods (please provide graph)
````
[alphaopt1,fcn1,alphas1] = selregparam(V,K,r,'tikh','lr','Search','grid');
[alphaopt2,fcn2,alphas2] = selregparam(V,K,r,'tikh','lr','Search','golden');

plot(log(alphas1),fcn1,log(alphas2),fcn2)
grid on,axis tight, box on
````

It could be that the LR-functional for these cases is not convex enough for the golden-search algorithm to efficiently find the optimum or it could be that there is a bug somewhere else.

**Comment by gjeschke** [comment]
Test 1:
No, I can't recover the old results. In one case, 0.8.beta returns (without 'Search' specification)

`Optimal alpha value: 100.00`

whereas the current commit returns

`Optimal alpha values: 501.19, 472.31`

for grid search and golden rule, respectively.

Test 2:

This test does not run (fcn1 and fcn2 are not valid arguments for plotting).

**Comment by luisfabib** [comment]
For test 2: my apologies, the function returns a cell array for the functionals. I have changed this so that when a single functional is evalluated it is not returned inside a cell.

**Comment by luisfabib** [comment]
However, your results show that the issue does not come from the golden-search failing in contrast to the grid-search. Therefore, the difference must have arisen in some other change. This will require a more in depth analysis by my part.

**Comment by stestoll** [comment]
It appears that there is no test for this, since all `selregparam` tests pass. Please add a test for this.

**Comment by luisfabib** [comment]
Yeah I agree. All tests were until now testing the relative alpha values between selection methods returned by ``selregparam``. I will add tests for absolute value control. It is, however, strange that this was not caughty by the ``fitregmodel`` tests, since they use ``selregaram`` to optimize the alphas, and there the absolute value of the fit quality is tested. 

As said in my previous comment, I will look into it.

**Comment by stestoll** [comment]
Here is a brief script that shows the problem with `'lr'` (and also `'lc'`). Most other selection methods (`'aic'`, `'gcv'`, etc.) work correctly.
```matlab
clear, clc

N = 201;
r = linspace(1,6,N);
Pmodel = rd_onegaussian(r,[3 0.3]);
t = linspace(0,3,N);
K = dipolarkernel(t,r);
V = K*Pmodel;
rng(2);
V = V + whitegaussnoise(N,0.02);

srch = 'golden';
alpha1 = selregparam(V,K,r,'tikhonov','lr','Search',srch)
alpha2 = selregparam(V,K,r,'tikhonov','aic','Search',srch)

Pfit1 = fitregmodel(V,K,r,'tikhonov',alpha1);
Pfit2 = fitregmodel(V,K,r,'tikhonov',alpha2);
Vfit1 = K*Pfit1;
Vfit2 = K*Pfit2;

subplot(2,1,1)
plot(t,V,t,Vfit1,t,Vfit2);
subplot(2,1,2)
plot(r,Pmodel,r,Pfit1,r,Pfit2);
```

**Comment by luisfabib** [comment]
I have identified the issue. The problem (as @stestoll has pointed out) is limited to the L-curve methods, namely ``lr`` and ``lc``. In this case, however, it is not a degradation of the optimization. The selection methods ``lr`` and ``lc`` were downright broken at a9c95ffea7ae74d93a0e6e65a8a845f6a3bd6d6a . 

The problem is that ``selregparam`` now evaluates the selection functionals for each alpha-value individually, so that the same function can be used for the different parameter search methods. However, the ``lr`` and ``lc`` methods require the fully evaluated alpha-range to work as they evaluate operators such as ``gradient`` and ``min``/``max``. Currently, for each of these operators, a ``0`` is returned and subsequent division leads to a ``NaN`` functional value for each alpha.  Since the ``min``/``max`` functions in MATLAB return ``NaN`` without an error, the largest alpha-value in the evaluation was being selected as optimal. 

A fix will follow ASAP.

**Comment by luisfabib** [comment]
Another important realization is, that L-curve methods are incompatible with a golden-search. The LR and LC criteria to determine the "elbow" of the L-curve requilre a fully evaluated and uniformly defined alpha-range. The golden-search selects the alpha values on the fly and cannot hence perform a search on a functional which changes depending on the evaluated alpha-values. 

Therefore, I have isolated the L-curve methods as grid-search exclusive. If the user requests LR or LC with a golden-search, the program will prompt an error with a guide on how to properly setup the grid-search. Namely the error message reads:

````
The 'lr' and 'lc' selection methods are not compatible with the
golden-search algorithm. Use the option selregparam(...,'Search','grid')
to enable their use.
````

All tests are passing and running the script provided above by @stestoll  now returns similar optimal values of alpha.

![untitled](https://user-images.githubusercontent.com/48292540/75088545-0c939f80-554f-11ea-9ebb-7b61d90fde0e.png)

@gjeschke to use the L-curve now, you need to call ``selregparam`` as follows:
````
alphaopt = selregparam(V,K,r,'tikh','lr','Search','grid');
````

Issue closed.
