### ISSUE TITLE
fitmultirice etc

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#54]
`fitmultigauss` is a convenient interface for using Gauss functions as basis functions. It would be good to have a similar function `fitmultirice` for 3D-Rice basis functions, and maybe others. The challenge is not to repeat code.

**Comment by luisfabib** [comment]
Agreed, I found that same issue today and I am already working on design ideas.

I believe the code repetition is not a problem, since we can always put the core mechanics into a private function. The question is rather: 

- do we want single functions: ``fitmultigauss``, ``fitmultirice``,...
- or rather a ``fitmultimodel`` with option to select the basis function?

**Comment by stestoll** [comment]
It should work with any mixture model, so `fitmixmodel` would be a suitable working name for now. My recent improvements to `mixmodels` (cae2a5c8d33b08e9fb7680b4708eaacd2f672196) probably improved performance of non-hard-coded mixture models sufficiently that this could be possible. (I haven't tested the performance though).

**Comment by luisfabib** [comment]
The current prototype `fitmultimodel` works for a general multi-component distribution using any of the built-in models as basis functions. 

The current limitation/problem lies in the optional specification of boundaries. Since now the basis functions can have different parameters, including the amplitudes introduced by `mixmodels` makes the indexing of the different parameters in the mixed models complex. 

In order to solve this, #55 must be solved first. Then, solving this issue will be trivial.
