### ISSUE TITLE
Inaccurate excitation bandwidth treatment in dipolarkernel

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#69]
`dipolarkernel` has an option `'ExcitationBandwidth'` to provide an excitation bandwidth for a Gaussian frequency-domain low-pass filter. However, internally, this does not appear to be treated correctly. The following example shows that the shape of the returned signal is inconsistent with a manual calculation using a gridded powder average.

```matlab
clear, clc, clf

% Parameters
r = 2.5; % nm
excitewidth = 30; % MHz
t = linspace(0,2,1001); % us

% (1) Reference signal with infinite bandwidth
Kinf = dipolarkernel(t,r,'ExcitationBandwidth',inf);

% (2) Signal using Fresnel integrals and approx. bandwidth treatment
K0 = dipolarkernel(t,r,'ExcitationBandwidth',excitewidth);

% (3) Manual calculation using numerical powder average
K1 = zeros(numel(t),numel(r));
nKnots = 10000;
costheta = linspace(0,1,nKnots);
wdd = 2*pi*52.04./r.^3; % Mrad/s
q = 1-3*costheta.^2;
for ir = 1:numel(wdd)
  D_ = 0;
  for itheta = 1:nKnots
    w = wdd(ir)*q(itheta);
    D_ = D_ + cos(w*abs(t)).*exp(-w.^2/excitewidth^2);
  end
  K1(:,ir) = D_/nKnots;
end

% Plotting
subplot(2,1,1)
plot(t,K0,t,K1,t,Kinf,'--k');
legend('Fresnel','grid','inf bw');
title('as calculated');

subplot(2,1,2)
plot(t,K0/K0(1),t,K1/K1(1),t,Kinf/Kinf(1),'--k');
legend('approx','exact','inf bw');
title('normalized to K(0)=1');
```

**Comment by luisfabib** [comment]
Yes, there are two errors currently with how the limited excitation bandwidth is handled: 

- **Error 1:** The Gaussian lowpass filter is applied at the end of the function to the whole constructed dipolar kernel (i.e. may contain multipe pathways and/or background). The filter should be only applied to the kernel matrix. 

- **Error 2:** the Gaussian filter is computed only from the dipolar frequencies without any orientational averaging.

This has two consequences: 

- The filtering has to be made part of the kernel matrix anonymous functions to include the averaging

- Compensation of limited excitation bandwidth is not compatible with a dipolar kernel constructed from the Fresnel integrals since they are no longer the result of the orientation averaging integral when including the Gaussian filter. 

There is an error in the corresponding equation of the DeerAnalysis documentation Eq.(12), which led to Error 2.
