### ISSUE TITLE
nlsqbnd solver does not work on Mac and Linux

### ISSUE THREAD

**Issue by stestoll** [luisfabib/DeerAnalysis2#74]
`private/nlsqbnd.m` calls a mex function `private/elsunc.mex*`. However, only Windows mex files are included.

**Comment by luisfabib** [comment]
I am aware of that. That's the reason, there is a OS check for the usage of ``nlsqbnd`` on the corresponding call functions. 

The function `nlsqbnd.m` is a wrapper function for the `elsunc` solver compiled as a MEX function. The issue is, that the author of  `nlsqbnd.m` does not provide any MEX files for other OS. I tried to contact the author, but got no answer back.

 The `elsunc` is part of a large solver package for which I managed to get the original FORTRAN source file. However, I have not managed to successfully compile it to a MEX file.

**Comment by stestoll** [comment]
Can one use Levenberg-Marquardt with transformed parameters, e.g. for parameter `x` with bounds `a` and `b` use `xt = log((x-a)/(b-a))`? Here is a link to other possible transformations: https://lmfit.github.io/lmfit-py/bounds.html

Also, EasySpin's `esfit_levmar` has bounds implemented by just clipping the parameters in every iteration. This might not be sound theoretically, but it's usable. There might be better options.

**Comment by luisfabib** [comment]
In this context it would make more sense to work with a logistic transformation, since it makes the parameter transformation constant outside of the boundaries in contrast to the sinusoidal behavior of the transformation of the link you shared. 

I would propose the following transformation: 

![CodeCogsEqn](https://user-images.githubusercontent.com/48292540/80349606-c8cf5600-886f-11ea-9f08-acb3c32db9aa.png)

which looks like this

![untitled](https://user-images.githubusercontent.com/48292540/80349852-25cb0c00-8870-11ea-8e99-2130c7aadd38.png)

and has some advantages

- A very clear definition of the boundaries
- Does not oscillate, i.e. derivative outside of boundaries stays the same
- Normalized, all parameters are internally normalized to a search in range `[0,1]` meaning that the whole search space is an N-dimensional surface in the range `[0,1]`.

UPDATE:  while some tests using this system worked, in general, convergence to the optimal solution was not achieved.

**Comment by luisfabib** [comment]
I added a new toolbox-free LSQ-specific solver `lmlsqnonlin` which behaves analogously to the toolbox solver `lsqnonlin`. This is based on the Levenberg-Marquardt and Jacobian toolboxes from Alexander Dentler in the File Exchange. 

This function is now the default solver for `fitparamodel` if the Optimization toolbox is not licensed or installed. Otherwise, `lsqnonlin` is still used as a default. 

Here is a benchmark of the `fitparamodel` tests for the toolbox-installed (`lsqnonlin`) vs. non-installed (`lmlsqnonlin`) cases: 

![Picture1](https://user-images.githubusercontent.com/48292540/80570941-ff39dc00-89fb-11ea-8b4d-01265eabec7f.png)

- the `lmlsqnonlin` seems to work pretty well with a slight decrease in precision which should be expected from a non built-in solver.
- the performance in cases where the `MultiStart` option is used appears to be awful. The origin of this is still unclear.
