### ISSUE TITLE
fitsignal CI evaluation's considerable slowdown

### ISSUE THREAD

**Issue by luisfabib** [luisfabib/DeerAnalysis2#80]
In `fitsignal` if the `paramci` output is requested, the confidence intervals of the fit parameters are evaluated. 
````matlab
t = linspace(0,5,100);
r = linspace(2,6,200);
P = dd_gauss(r,[4.5 0.6]);
V = dipolarsignal(t,r,P,0.3,'noiselevel',0.01);

% Parameters CI not evaluated
tic
[Vfit,Pfit,Bfit,parfit] = fitsignal(V,t,r,'P','none');
toc

% Parameters CI evaluated
tic
[Vfit,Pfit,Bfit,parfit,paramci] = fitsignal(V,t,r,'P','none');
toc
````
this leads to a considerable slow-down when using parameter-free distributions
````
Elapsed time is 0.780865 seconds.
Elapsed time is 18.600751 seconds.
````
The reason for this, is that by default `fitparamodel` evaluates a numerical Jacobian of the model function being fitted. Since in `fitsignal` the model contains an evaluation via `fitregmodel`, which leads to a costly Jacobian evaluation. 

At the moment I am not sure of.... 

- ...how this to achieve a speed-up of this.
- ...whether the evaluation of the Jacobian this way is theoretically sound.

**Comment by stestoll** [comment]
Most of the time in the Jacobian estimation is spent in `selregparam` to optimize `alpha` for each model call from `jacobianest`. Our current heuristic of detecting small parameter steps doesn't work int this case, because `jacobianest` does some quite big steps as well (in contrast to the lsq solves).

Besides reducing the number of function calls needed to calculate the Jacobian, the only way to speed this up is to fix `alpha` during Jacobian calculation. Theoretically, this is different from optimizing it at each step, but it's possible that the difference is not significant.

**Comment by luisfabib** [comment]
The way the CIs are handled for cases with parameter-free distributions has been re-worked according to error propagation theory. The evaluation is widely faster due to the Jacobian being mostly computed analytically with only a submatrix needing numerical estimation.
